pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=test (ubuntu-latest)
      - check-success=test (macos-latest)
      - check-success=test (windows-latest)
      - check-success=docker-build
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
